package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IopushIsp generated by hbm2java
 */
@Entity
@Table(name="iopush_isp"
    ,schema="public"
)
public class IopushIsp  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ispId;
     private String ispName;
     private int countryId ;
     private Set<IopushSubscribers> iopushSubscribers = new HashSet<IopushSubscribers>(0);

    public IopushIsp() {
    }

	
    public IopushIsp(int ispId) {
        this.ispId = ispId;
    }
    public IopushIsp(int ispId, String ispName, Set<IopushSubscribers> iopushSubscribers) {
       this.ispId = ispId;
       this.ispName = ispName;
       this.iopushSubscribers = iopushSubscribers;
    }
   
    @Id   
    @SequenceGenerator(name="iopush_isp_seq", sequenceName="iopush_isp_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_isp_seq")
    @Column(name = "isp_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getIspId() {
        return this.ispId;
    }
    
    public void setIspId(int ispId) {
        this.ispId = ispId;
    }

    
    @Column(name="isp_name", length=100)
    public String getIspName() {
        return this.ispName;
    }
    
    public void setIspName(String ispName) {
        this.ispName = ispName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushIsp")
    public Set<IopushSubscribers> getIopushSubscribers() {
        return this.iopushSubscribers;
    }
    
    public void setIopushSubscribers(Set<IopushSubscribers> iopushSubscribers) {
        this.iopushSubscribers = iopushSubscribers;
    }

    @Column(name="fk_countryid")
	public int getCountryId() {
		return countryId;
	}


	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}




}


