package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushRules generated by hbm2java
 */
@Entity
@Table(name="iopush_rules"
    ,schema="public"
)
public class IopushRules  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ruleId;
     private IopushCampaign iopushCampaign;
     private String createdBy;
     private Date creationDate;
     private Date modificationDate;
     private String modificedBy;
     private String ruleType;
     private String ruleValue;

    public IopushRules() {
    }

	
    public IopushRules(int ruleId, IopushCampaign iopushCampaign, Date modificationDate) {
        this.ruleId = ruleId;
        this.iopushCampaign = iopushCampaign;
        this.modificationDate = modificationDate;
    }
    public IopushRules(int ruleId, IopushCampaign iopushCampaign, String createdBy, Date creationDate, Date modificationDate, String modificedBy, String ruleType, String ruleValue) {
       this.ruleId = ruleId;
       this.iopushCampaign = iopushCampaign;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.modificedBy = modificedBy;
       this.ruleType = ruleType;
       this.ruleValue = ruleValue;
    }
   
    public IopushRules(IopushCampaign iopushCampaign, String ruleType, String ruleValue, 
			Date creationDate,String createdBy, Date modificationDate, String modificedBy) {
		this.iopushCampaign = iopushCampaign;
		this.ruleType = ruleType;
		this.ruleValue = ruleValue;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.modificationDate = modificationDate;
		this.modificedBy = modificedBy;
	}


	@Id   
    @SequenceGenerator(name="iopush_rules_seq", sequenceName="iopush_rules_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_rules_seq")
    @Column(name = "rules_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(int ruleId) {
        this.ruleId = ruleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_campaign_id", nullable=false)
    public IopushCampaign getIopushCampaign() {
        return this.iopushCampaign;
    }
    
    public void setIopushCampaign(IopushCampaign iopushCampaign) {
        this.iopushCampaign = iopushCampaign;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modification_date", nullable=false, length=29)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="modificed_by", length=50)
    public String getModificedBy() {
        return this.modificedBy;
    }
    
    public void setModificedBy(String modificedBy) {
        this.modificedBy = modificedBy;
    }

    
    @Column(name="rule_type", length=50)
    public String getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }

    
    @Column(name="rule_value", length=200)
    public String getRuleValue() {
        return this.ruleValue;
    }
    
    public void setRuleValue(String ruleValue) {
        this.ruleValue = ruleValue;
    }






}


