package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushCampaign generated by hbm2java
 */
@Entity
@Table(name="iopush_welcome"
,schema="public"
) 
		
public class IopushWelcome  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int welcomeId;
	private IopushProduct iopushProduct;
	private String segment_id;
	private String segmentType_id;
	/**
	 * @return the segment_id
	 */
	@Column(name="segment_id", length=500)
	public String getSegment_id() {
		return segment_id;
	}



	/**
	 * @param segment_id the segment_id to set
	 */
	public void setSegment_id(String segment_id) {
		this.segment_id = segment_id;
	}



	/**
	 * @return the segmentType_id
	 */
	@Column(name="segmentType_id", length=500)
	public String getSegmentType_id() {
		return segmentType_id;
	}



	/**
	 * @param segmentType_id the segmentType_id to set
	 */
	public void setSegmentType_id(String segmentType_id) {
		this.segmentType_id = segmentType_id;
	}



	/**
	 * @return the iopushSegmentType
	 */




	private Integer welcomeclick;
	private Integer welcomeclose;
//	private String welcomeCurrentDate;
	private String welcomeName; 
	private String source;
	private String generic;
	private String campaign;
	private Integer welcomeopen;
	private Integer welcomesent;
	private String welcomeScheduleDate;
	private Date welcomeScheduleDateInEdt;
	private String welcomeEndDate;
	private Date welcomeEndDateInEdt;
	private int welcomeStatus;
	private String createdBy;
	private Date creationDate;
	private Date modificationDate;
	private String modificedBy;
	private String title;
    private String description;
    private String forwardUrl;
    private String imagePath;
    private boolean unlimited;
    private boolean segmented;
	private String platform;
	private String countries;
	private String cities;
	private String isps;
	private String subscribed;
	private String segmentSelected;
	private boolean active;
	//private boolean requireInteraction;
	
//  Banner Image Fields
	private boolean largeImage;
	private String bannerImage;

	/**
	 * @return the subscribed
	 */
	@Column(name="welcome_subscribed_date", length=29)
	public String getSubscribed() {
		return subscribed;
	}



	/**
	 * @param subscribed the subscribed to set
	 */
	public void setSubscribed(String subscribed) {
		this.subscribed = subscribed;
	}



	public IopushWelcome() {
	}



		/**
	 * @return the segmentSelected
	 */
	@Column(name="segment_selected", length=60)
	public String getSegmentSelected() {
		return segmentSelected;
	}



	/**
	 * @param segmentSelected the segmentSelected to set
	 */
	public void setSegmentSelected(String segmentSelected) {
		this.segmentSelected = segmentSelected;
	}



		/**
	 * @return the welcomeId
	 */
	 @Id   
	    @SequenceGenerator(name="iopush_welcome_seq", sequenceName="iopush_welcome_seq",allocationSize=1)
	 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_welcome_seq")
	 @Column(name = "welcome_id", unique = true, nullable = false,columnDefinition = "serial")
	public int getWelcomeId() {
		return welcomeId;
	}




	/**
	 * @param welcomeId the welcomeId to set
	 */
	 
	public void setWelcomeId(int welcomeId) {
		this.welcomeId = welcomeId;
	}




	/**
	 * @return the iopushProduct
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="fk_product_id", nullable=false)
	public  IopushProduct getIopushProduct() {
		return iopushProduct;
	}




	/**
	 * @param iopushProduct the iopushProduct to set
	 */
	public void setIopushProduct(IopushProduct iopushProduct) {
		this.iopushProduct = iopushProduct;
	}

	/**
	 * @return the welcomeclick
	 */
	@Column(name="welcomeclick", columnDefinition = "int default 0")
	public Integer getWelcomeclick() {
		return welcomeclick;
	}

	/**
	 * @param welcomeclick the welcomeclick to set
	 */
	public void setWelcomeclick(Integer welcomeclick) {
		this.welcomeclick = welcomeclick;
	}

	/*@Column(name="reqiureInteraction")
	public boolean isRequireInteraction() {
		return requireInteraction;
	}
	public void setRequireInteraction(boolean requireInteraction) {
		this.requireInteraction = requireInteraction;
	}*/

	/**
	 * @return the welcomeclose
	 */

	@Column(name="welcomeclose", columnDefinition = "int default 0")
	public Integer getWelcomeclose() {
		return welcomeclose;
	}




	/**
	 * @param welcomeclose the welcomeclose to set
	 */
	public void setWelcomeclose(Integer welcomeclose) {
		this.welcomeclose = welcomeclose;
	}




	/**
	 * @return the welcomeName
	 */
	@Column(name="welcome_name", length=60)
	public String getWelcomeName() {
		return welcomeName;
	}




	/**
	 * @param welcomeName the welcomeName to set
	 */
	public void setWelcomeName(String welcomeName) {
		this.welcomeName = welcomeName;
	}




	/**
	 * @return the source
	 */
	@Column(name="source", length=60)
	public String getSource() {
		return source;
	}




	/**
	 * @param source the source to set
	 */
	public void setSource(String source) {
		this.source = source;
	}




	/**
	 * @return the generic
	 */
	@Column(name="generic", length=60)
	public String getGeneric() {
		return generic;
	}




	/**
	 * @param generic the generic to set
	 */
	public void setGeneric(String generic) {
		this.generic = generic;
	}




	/**
	 * @return the welcomeopen
	 */
	@Column(name="welcomeopen", columnDefinition = "int default 0")
	public Integer getWelcomeopen() {
		return welcomeopen;
	}




	/**
	 * @param welcomeopen the welcomeopen to set
	 */
	public void setWelcomeopen(Integer welcomeopen) {
		this.welcomeopen = welcomeopen;
	}




	/**
	 * @return the welcomesent
	 */
	@Column(name="welcomesent", columnDefinition = "int default 0")
	public Integer getWelcomesent() {
		return welcomesent;
	}




	/**
	 * @param welcomesent the welcomesent to set
	 */
	public void setWelcomesent(Integer welcomesent) {
		this.welcomesent = welcomesent;
	}




	/**
	 * @return the welcomeScheduleDate
	 */
	@Column(name="welcome_schedule_date", length=29)
	public String getWelcomeScheduleDate() {
		return welcomeScheduleDate;
	}




	/**
	 * @param welcomeScheduleDate the welcomeScheduleDate to set
	 */
	public void setWelcomeScheduleDate(String welcomeScheduleDate) {
		this.welcomeScheduleDate = welcomeScheduleDate;
	}




	/**
	 * @return the welcomeScheduleDateInEdt
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="welcome_schedule_date_in_edt", length=29)
	public Date getWelcomeScheduleDateInEdt() {
		return welcomeScheduleDateInEdt;
	}




	/**
	 * @param welcomeScheduleDateInEdt the welcomeScheduleDateInEdt to set
	 */
	public void setWelcomeScheduleDateInEdt(Date welcomeScheduleDateInEdt) {
		this.welcomeScheduleDateInEdt = welcomeScheduleDateInEdt;
	}




	/**
	 * @return the welcomeEndDate
	 */
	@Column(name="welcome_end_date", length=29)
	public String getWelcomeEndDate() {
		return welcomeEndDate;
	}




	/**
	 * @param welcomeEndDate the welcomeEndDate to set
	 */
	public void setWelcomeEndDate(String welcomeEndDate) {
		this.welcomeEndDate = welcomeEndDate;
	}




	/**
	 * @return the welcomeEndDateInEdt
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="welcome_end_date_in_edt", length=29)
	public Date getWelcomeEndDateInEdt() {
		return welcomeEndDateInEdt;
	}




	/**
	 * @param welcomeEndDateInEdt the welcomeEndDateInEdt to set
	 */
	public void setWelcomeEndDateInEdt(Date welcomeEndDateInEdt) {
		this.welcomeEndDateInEdt = welcomeEndDateInEdt;
	}




	/**
	 * @return the welcomeStatus
	 */
	@Column(name="welcome_status", nullable=false)
	public int getWelcomeStatus() {
		return welcomeStatus;
	}




	/**
	 * @param welcomeStatus the welcomeStatus to set
	 */
	public void setWelcomeStatus(int welcomeStatus) {
		this.welcomeStatus = welcomeStatus;
	}




	/**
	 * @return the createdBy
	 */
	@Column(name="created_by", length=50)
	public String getCreatedBy() {
		return createdBy;
	}




	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}




	/**
	 * @return the creationDate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="creation_date", length=29)
	public Date getCreationDate() {
		return creationDate;
	}




	/**
	 * @param creationDate the creationDate to set
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}




	/**
	 * @return the modificationDate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="modification_date", nullable=false, length=29)
	public Date getModificationDate() {
		return modificationDate;
	}




	/**
	 * @param modificationDate the modificationDate to set
	 */
	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}




	/**
	 * @return the modificedBy
	 */
	@Column(name="modificed_by", length=50)
	public String getModificedBy() {
		return modificedBy;
	}




	/**
	 * @param modificedBy the modificedBy to set
	 */
	public void setModificedBy(String modificedBy) {
		this.modificedBy = modificedBy;
	}




	/**
	 * @return the title
	 */
	 @Column(name="title", length=200)
	public String getTitle() {
		return title;
	}




	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}




	/**
	 * @return the description
	 */
	 @Column(name="description", length=200)
	public String getDescription() {
		return description;
	}




	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}




	/**
	 * @return the forwardUrl
	 */
	 @Column(name="forward_url", length=200)
	public String getForwardUrl() {
		return forwardUrl;
	}




	/**
	 * @param forwardUrl the forwardUrl to set
	 */
	public void setForwardUrl(String forwardUrl) {
		this.forwardUrl = forwardUrl;
	}




	/**
	 * @return the imagePath
	 */
	  @Column(name="image_path", length=1000)
	public String getImagePath() {
		return imagePath;
	}




	/**
	 * @param imagePath the imagePath to set
	 */
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}



	/**
	 * @return the segmented
	 */
	@Column(name="is_segmented")
	public boolean isSegmented() {
		return segmented;
	}




	/**
	 * @param segmented the segmented to set
	 */
	public void setSegmented(boolean segmented) {
		this.segmented = segmented;
	}





	/**
	 * @return the platform_id
	 */
	@Column(name="platforms", length=60)
	public String getPlatform() {
		return platform;
	}




	/**
	 * @param platform_id the platform_id to set
	 */
	public void setPlatform(String platform) {
		this.platform = platform;
	}




	/**
	 * @return the geo_id
	 */
	@Column(name="countries", length=60)
	public String getCountries() {
		return countries;
	}




	/**
	 * @param geo_id the geo_id to set
	 */
	public void setCountries(String countries) {
		this.countries = countries;
	}




	/**
	 * @return the city_id
	 */
	@Column(name="cities", length=60)
	public String getCities() {
		return cities;
	}




	/**
	 * @param city_id the city_id to set
	 */
	public void setCities(String cities) {
		this.cities = cities;
	}




	/**
	 * @return the isps
	 */
	@Column(name="isps", length=200)
	public String getIsps() {
		return isps;
	}




	/**
	 * @param isps the isps to set
	 */
	public void setIsps(String isps) {
		this.isps = isps;
	}





	@Column(name="unlimited", nullable=false)
	public boolean isUnlimited() {
		return unlimited;
	}



	public void setUnlimited(boolean unlimited) {
		this.unlimited = unlimited;
	}


	@Column(name="campaign", length=60)
	public String getCampaign() {
		return campaign;
	}



	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}


	@Column(name="active", nullable=false)
	public boolean isActive() {
		return active;
	}



	public void setActive(boolean active) {
		this.active = active;
	}


	/**
	 * @return the largeImage
	 */
	@Column(name="large_image" )
	public boolean isLargeImage() {
		return largeImage;
	}


	/**
	 * @param largeImage the largeImage to set
	 */
	public void setLargeImage(boolean largeImage) {
		this.largeImage = largeImage;
	}


	/**
	 * @return the bannerImage
	 */
	@Column(name="banner_image", length=120)
	public String getBannerImage() {
		return bannerImage;
	}


	/**
	 * @param bannerImage the bannerImage to set
	 */
	public void setBannerImage(String bannerImage) {
		this.bannerImage = bannerImage;
	}
	    
	
	
}


