package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IopushUserplan generated by hbm2java
 */
@Entity
@Table(name="iopush_plan"
    ,schema="public"
)
public class IopushUserplan  implements java.io.Serializable {


     /**
  * 
  */
 private static final long serialVersionUID = 1L;
 private int planId;
     private String planName;
     private int pricing;
     private int subscriberLimit;
     //private Set<IopushUsercategory> iopushUsercategories = new HashSet<IopushUsercategory>(0);
     private boolean isRenew;
     //private double cost;
     private String symbol;
     private String currencyName;
     private Date duration;

    public IopushUserplan() {
    }

 
    public IopushUserplan(int planId, String planName, int pricing, int subscriberLimit) {
        this.planId = planId;
        this.planName = planName;
        this.pricing = pricing;
        this.subscriberLimit = subscriberLimit;
    }
    public IopushUserplan(int planId, String planName, int pricing, int subscriberLimit, Set<IopushUsercategory> iopushUsercategories) {
       this.planId = planId;
       this.planName = planName;
       this.pricing = pricing;
       this.subscriberLimit = subscriberLimit;
     //  this.iopushUsercategories = iopushUsercategories;
    }
   
    public IopushUserplan(int planID2) {
  // TODO Auto-generated constructor stub
     this.planId=planID2;
 }


 @Id   
    @SequenceGenerator(name="iopush_userplan_seq", sequenceName="iopush_userplan_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_userplan_seq")
    @Column(name = "userplan_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }

    
    @Column(name="plan_name", nullable=false, length=15)
    public String getPlanName() {
        return this.planName;
    }
    
    public void setPlanName(String planName) {
        this.planName = planName;
    }

    
    @Column(name="pricing", nullable=false)
    public int getPricing() {
        return this.pricing;
    }
    
    public void setPricing(int pricing) {
        this.pricing = pricing;
    }

    
    @Column(name="subscriber_limit", nullable=false)
    public int getSubscriberLimit() {
        return this.subscriberLimit;
    }
    
    public void setSubscriberLimit(int subscriberLimit) {
        this.subscriberLimit = subscriberLimit;
    }

/*@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushUserplan")
    public Set<IopushUsercategory> getIopushUsercategories() {
        return this.iopushUsercategories;
    }
    
    public void setIopushUsercategories(Set<IopushUsercategory> iopushUsercategories) {
        this.iopushUsercategories = iopushUsercategories;
    }*/

    @Column(name="isRenew")
 public boolean isRenew() {
  return isRenew;
 }


 public void setRenew(boolean isRenew) {
  this.isRenew = isRenew;
 }


/* public double getCost() {
  return cost;
 }
*/

/* public void setCost(double cost) {
  this.cost = cost;
 }
*/

 public String getSymbol() {
  return symbol;
 }


 public void setSymbol(String symbol) {
  this.symbol = symbol;
 }


 public String getCurrencyName() {
  return currencyName;
 }


 public void setCurrencyName(String currencyName) {
  this.currencyName = currencyName;
 }


 public Date getDuration() {
  return duration;
 }


 public void setDuration(Date duration) {
  this.duration = duration;
 }




}