package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IopushCampaignStats generated by hbm2java
 */
@Entity
@Table(name="iopush_campaign_stats"
    ,schema="public", uniqueConstraints = @UniqueConstraint(columnNames={"fk_campaign_id", "cityid","geoid","platformid"}) 
)
public class IopushCampaignStats  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int statsId;
     private IopushCampaign iopushCampaign;
     private int campaignclick;
     private int campaignclose;
     private int campaignopen;
     private int campaignsent;
     private int cityid;
     private int geoid;
     private int platformid;

    public IopushCampaignStats() {
    }

    public IopushCampaignStats(int statsId, IopushCampaign iopushCampaign, int campaignclick, int campaignclose, int campaignopen, int campaignsent, int cityid, int geoid, int platformid) {
       this.statsId = statsId;
       this.iopushCampaign = iopushCampaign;
       this.campaignclick = campaignclick;
       this.campaignclose = campaignclose;
       this.campaignopen = campaignopen;
       this.campaignsent = campaignsent;
       this.cityid = cityid;
       this.geoid = geoid;
       this.platformid = platformid;
    }
    
    @Id
    @SequenceGenerator(name="iopush_campaign_stats_seq", sequenceName="iopush_campaign_stats_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_campaign_stats_seq")
    @Column(name = "stats_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getStatsId() {
        return this.statsId;
    }
    
    public void setStatsId(int statsId) {
        this.statsId = statsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_campaign_id", nullable=false)
    public IopushCampaign getIopushCampaign() {
        return this.iopushCampaign;
    }
    
    public void setIopushCampaign(IopushCampaign iopushCampaign) {
        this.iopushCampaign = iopushCampaign;
    }

    
    @Column(name="campaignclick", columnDefinition = "int default 0")
    public int getCampaignclick() {
        return this.campaignclick;
    }
    
    public void setCampaignclick(int campaignclick) {
        this.campaignclick = campaignclick;
    }

    
    @Column(name="campaignclose", columnDefinition = "int default 0")
    public int getCampaignclose() {
        return this.campaignclose;
    }
    
    public void setCampaignclose(int campaignclose) {
        this.campaignclose = campaignclose;
    }

    
    @Column(name="campaignopen", columnDefinition = "int default 0")
    public int getCampaignopen() {
        return this.campaignopen;
    }
    
    public void setCampaignopen(int campaignopen) {
        this.campaignopen = campaignopen;
    }

    
    @Column(name="campaignsent", columnDefinition = "int default 0")
    public int getCampaignsent() {
        return this.campaignsent;
    }
    
    public void setCampaignsent(int campaignsent) {
        this.campaignsent = campaignsent;
    }

    
    @Column(name="cityid", nullable=false)
    public int getCityid() {
        return this.cityid;
    }
    
    public void setCityid(int cityid) {
        this.cityid = cityid;
    }

    
    @Column(name="geoid", nullable=false)
    public int getGeoid() {
        return this.geoid;
    }
    
    public void setGeoid(int geoid) {
        this.geoid = geoid;
    }

    
    @Column(name="platformid", nullable=false)
    public int getPlatformid() {
        return this.platformid;
    }
    
    public void setPlatformid(int platformid) {
        this.platformid = platformid;
    }




}


