package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushCampaign generated by hbm2java
 */
@Entity
@Table(name="iopush_subcampaign"
,schema="public"

		)
public class IopushSubCampaign  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private int subcampaignId;
	 private IopushCampaign iopushCampaign;
	private String campaignName; 
	private String campaignScheduleDate;
	private Date campaignScheduleDateInEdt;
	private String campaignEndDate;
	private Date campaignEndDateInEdt;
	private int campaignStatus;
	private int eligiblecount;
	private int geoid;
	/**
	 * @return the geoid
	 */
	@Column(name="geo_id", nullable=false)
	public int getGeoid() {
		return geoid;
	}


	/**
	 * @param geoid the geoid to set
	 */
	public void setGeoid(int geoid) {
		this.geoid = geoid;
	}










	private IopushTimeZone iopushTimeZone;
	/**
	 * @return the country_id
	 */


	public IopushSubCampaign() {
	}


	public IopushSubCampaign(int subcampaignId, int campaignStatus, int eligiblecount) {
		
		this.subcampaignId = subcampaignId;
		this.campaignStatus = campaignStatus;
		this.eligiblecount = eligiblecount;
		
	}
	
	@OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "campaign_id" , nullable = false)
	public IopushCampaign getIopushCampaign() {
		return iopushCampaign;
	}
	public void setIopushCampaign(IopushCampaign iopushCampaign) {
		this.iopushCampaign = iopushCampaign;
	}

	@Id 
    @SequenceGenerator(name="iopush_subcampaign_seq", sequenceName="iopush_subcampaign_seq",allocationSize=1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_subcampaign_seq")
 @Column(name = "subcampaignId", unique = true, nullable = false,columnDefinition = "serial")
	public int getSubcampaignId() {
		return subcampaignId;
	}
	public void setSubcampaignId(int subcampaignId) {
		this.subcampaignId = subcampaignId;
	}



	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="fk_timezone_id", nullable=false)
	public IopushTimeZone getIopushTimeZone() {
		return this.iopushTimeZone;
	}

	public void setIopushTimeZone(IopushTimeZone fkTimezoneId) {
		this.iopushTimeZone = fkTimezoneId;
	}


	@Column(name="campaign_name", length=60)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Column(name="campaign_schedule_date", length=29)
	public String getCampaignScheduleDate() {
		return this.campaignScheduleDate;
	}

	public void setCampaignScheduleDate(String campaignScheduleDate) {
		this.campaignScheduleDate = campaignScheduleDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="campaign_schedule_date_in_edt", length=29)
	public Date getCampaignScheduleDateInEdt() {
		return this.campaignScheduleDateInEdt;
	}

	public void setCampaignScheduleDateInEdt(Date campaignScheduleDateInEdt) {
		this.campaignScheduleDateInEdt = campaignScheduleDateInEdt;
	}

	@Column(name="campaign_end_date", length=29)
	public String getCampaignEndDate() {
		return campaignEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="campaign_end_date_in_edt", length=29)
	public Date getCampaignEndDateInEdt() {
		return campaignEndDateInEdt;
	}


	public void setCampaignEndDate(String campaignEndDate) {
		this.campaignEndDate = campaignEndDate;
	}


	public void setCampaignEndDateInEdt(Date campaignEndDateInEdt) {
		this.campaignEndDateInEdt = campaignEndDateInEdt;
	}

	
	

	
	
	
	@Column(name="campaign_status", nullable=false)
	public int getCampaignStatus() {
		return this.campaignStatus;
	}

	

	public void setCampaignStatus(int campaignStatus) {
		this.campaignStatus = campaignStatus;
	}



	@Column(name="eligiblecount", nullable=false)
	public int getEligiblecount() {
		return this.eligiblecount;
	}

	public void setEligiblecount(int eligiblecount) {
		this.eligiblecount = eligiblecount;
	}


	
	




	

		@Override
		public String toString() {
			return "IopushCampaign [subcampaignId=" + subcampaignId +
					", campaignName=" + campaignName 
					+ ", campaignScheduleDate=" + campaignScheduleDate + ", campaignScheduleDateInEdt="
					+ campaignScheduleDateInEdt + ", campaignEndDate=" + campaignEndDate + ", campaignEndDateInEdt="
					+ campaignEndDateInEdt + ", campaignStatus=" + campaignStatus + ", eligiblecount=" + eligiblecount 
					 +"]";
		}

	    
		
		
	    
}


