package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushSubscribers generated by hbm2java
 */
@Entity
@Table(name="iopush_subscribers"
    ,schema="public"
)
public class IopushSubscribers  implements java.io.Serializable {


 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int subscriberId;
     private IopushPlatformCategory iopushPlatformcategory;
     private IopushGeoDetails iopushGeoDetails;
     private IopushCityDetails iopushCityDetails;
     private IopushIsp iopushIsp;
     private String fcmToken;
     private String osLanguage;
     private String osName;
     private String iopushToken;
     private IopushProduct iopushProduct;
     private Date installationDate;
     private IopushPlatformDetails iopushPlatformDetails;
     private int iopushSegmentation;
     private String ip;
     

    /**
	 * @return the ip
	 */
     @Column(name="ip", nullable=false, length=30)
	public String getIp() {
		return ip;
	}




	/**
	 * @param ip the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}




	public IopushSubscribers() {
    }




	public IopushSubscribers(int subscriberId, IopushPlatformCategory iopushPlatformcategory,
			IopushGeoDetails iopushGeoDetails, IopushCityDetails iopushCityDetails, IopushIsp iopushIsp,
			String fcmToken, String osLanguage, String osName, String iopushToken, IopushProduct iopushProduct,
			Date installationDate, IopushPlatformDetails iopushPlatformDetails, int iopushSegmentation, String ip) {
		super();
		this.subscriberId = subscriberId;
		this.iopushPlatformcategory = iopushPlatformcategory;
		this.iopushGeoDetails = iopushGeoDetails;
		this.iopushCityDetails = iopushCityDetails;
		this.iopushIsp = iopushIsp;
		this.fcmToken = fcmToken;
		this.osLanguage = osLanguage;
		this.osName = osName;
		this.iopushToken = iopushToken;
		this.iopushProduct = iopushProduct;
		this.installationDate = installationDate;
		this.iopushPlatformDetails = iopushPlatformDetails;
		this.iopushSegmentation = iopushSegmentation;
		this.ip = ip;
	}




	public IopushSubscribers(int subscriberId, IopushPlatformCategory iopushPlatformcategory, IopushGeoDetails iopushGeoDetails, IopushCityDetails iopushCityDetails, IopushIsp iopushIsp, String fcmToken, String osLanguage, String osName, String iopushToken, Date installationDate, IopushPlatformDetails iopushPlatformDetails) {
        this.subscriberId = subscriberId;
        this.iopushPlatformcategory = iopushPlatformcategory;
        this.iopushGeoDetails = iopushGeoDetails;
        this.iopushCityDetails = iopushCityDetails;
        this.iopushIsp = iopushIsp;
        this.fcmToken = fcmToken;
        this.osLanguage = osLanguage;
        this.osName = osName;
        this.iopushToken = iopushToken;
        this.installationDate = installationDate;
        this.iopushPlatformDetails=iopushPlatformDetails;
    }
   
   
    @Id   
    @SequenceGenerator(name="iopush_subscribers_seq", sequenceName="iopush_subscribers_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_subscribers_seq")
    
    @Column(name = "subscribers_id", unique = true, nullable = false,columnDefinition = "serial")    
    public int getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(int subscriberId) {
        this.subscriberId = subscriberId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_category_id", nullable=false)
    public IopushPlatformCategory getIopushPlatformcategory() {
        return this.iopushPlatformcategory;
    }
    
    public void setIopushPlatformcategory(IopushPlatformCategory iopushPlatformcategory) {
        this.iopushPlatformcategory = iopushPlatformcategory;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_geo_id", nullable=false)
    public IopushGeoDetails getIopushGeoDetails() {
        return this.iopushGeoDetails;
    }
    
    public void setIopushGeoDetails(IopushGeoDetails iopushGeoDetails) {
        this.iopushGeoDetails = iopushGeoDetails;
    }
    
	

    @Column(name="fk_segmentId", nullable=false)
	public int getIopushSegmentation() {
		return iopushSegmentation;
	}


	public void setIopushSegmentation(int iopushSegmentation) {
		this.iopushSegmentation = iopushSegmentation;
	}

	 @ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="fk_city_id", nullable=false)
    public IopushCityDetails getIopushCityDetails() {
        return this.iopushCityDetails;
    }
    
    public void setIopushCityDetails(IopushCityDetails iopushCityDetails) {
        this.iopushCityDetails = iopushCityDetails;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_isp_id", nullable=false)
    public IopushIsp getIopushIsp() {
        return this.iopushIsp;
    }
    
    public void setIopushIsp(IopushIsp iopushIsp) {
        this.iopushIsp = iopushIsp;
    }

    
    @Column(name="fcm_token", nullable=false)
    public String getFcmToken() {
        return this.fcmToken;
    }
    
    public void setFcmToken(String fcmToken) {
        this.fcmToken = fcmToken;
    }

    
    @Column(name="os_language", nullable=false)
    public String getOsLanguage() {
        return this.osLanguage;
    }
    
    public void setOsLanguage(String osLanguage) {
        this.osLanguage = osLanguage;
    }

    
    @Column(name="os_name", nullable=false)
    public String getOsName() {
        return this.osName;
    }
    
    public void setOsName(String osName) {
        this.osName = osName;
    }

    
    @Column(name="iopush_token", nullable=false,unique=true)
    public String getIopushToken() {
        return this.iopushToken;
    }
    
    public void setIopushToken(String iopushToken) {
        this.iopushToken = iopushToken;
    }

    
    
    /**
	 * @return the iopushProduct
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_product_id", nullable=false)
	public IopushProduct getIopushProduct() {
		return iopushProduct;
	}


	/**
	 * @param iopushProduct the iopushProduct to set
	 */
	public void setIopushProduct(IopushProduct iopushProduct) {
		this.iopushProduct = iopushProduct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="installation_date", nullable=false)
    public Date getInstallationDate() {
        return this.installationDate;
    }
    
    public void setInstallationDate(Date installationDate) {
        this.installationDate = installationDate;
    }

    
    
/**
	 * @return the iopushPlatformDetails
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_platform_id", nullable=false)
	public IopushPlatformDetails getIopushPlatformDetails() {
		return iopushPlatformDetails;
	}


	/**
	 * @param iopushPlatformDetails the iopushPlatformDetails to set
	 */
	public void setIopushPlatformDetails(IopushPlatformDetails iopushPlatformDetails) {
		this.iopushPlatformDetails = iopushPlatformDetails;
	}

    @Override
	public String toString() {
		return "IopushSubscribers [subscriberId=" + subscriberId + ", iopushPlatformcategory=" + iopushPlatformcategory
				+ ", iopushGeoDetails=" + iopushGeoDetails + ", iopushCityDetails=" + iopushCityDetails + ", iopushIsp="
				+ iopushIsp + ", fcmToken=" + fcmToken + ", osLanguage=" + osLanguage + ", osName=" + osName
				+ ", iopushToken=" + iopushToken + ", iopushProduct=" + iopushProduct + ", installationDate="
				+ installationDate + ", iopushPlatformDetails=" + iopushPlatformDetails + "]";
	}


}


