package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IopushAuthorityGroupMapping generated by hbm2java
 */
@Entity
@Table(name="iopush_authority_group_mapping"
    ,schema="public"
)
public class IopushAuthorityGroupMapping  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int mappingId;
     private IopushUser iopushUser;
     private IopushAuthority iopushAuthority;

    public IopushAuthorityGroupMapping() {
    }

    public IopushAuthorityGroupMapping(int mappingId, IopushUser iopushUser, IopushAuthority iopushAuthority) {
       this.mappingId = mappingId;
       this.iopushUser = iopushUser;
       this.iopushAuthority = iopushAuthority;
    }
   
    @Id   
    @SequenceGenerator(name="iopush_authority_group_mapping_seq", sequenceName="iopush_authority_group_mapping_seq",allocationSize=1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_authority_group_mapping_seq")
 @Column(name = "mapping_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getMappingId() {
        return this.mappingId;
    }
    
    public void setMappingId(int mappingId) {
        this.mappingId = mappingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_user_id", nullable=false)
    public IopushUser getIopushUser() {
        return this.iopushUser;
    }
    
    public void setIopushUser(IopushUser iopushUser) {
        this.iopushUser = iopushUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_auth_id", nullable=false)
    public IopushAuthority getIopushAuthority() {
        return this.iopushAuthority;
    }
    
    public void setIopushAuthority(IopushAuthority iopushAuthority) {
        this.iopushAuthority = iopushAuthority;
    }




}


