package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IopushCampaign generated by hbm2java
 */
@Entity
@Table(name="iopush_campaign"
,schema="public"
, uniqueConstraints = @UniqueConstraint(columnNames={"campaign_name", "fk_product_id",}) 
		)
public class IopushCampaign  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int campaignId;
	private IopushProduct iopushProduct;
	private Integer campaignclick;
	private Integer campaignclose;
	private String campaignCurrentDate;
	private String campaignName; 
	private String source;
	private String generic;
	private Integer campaignopen;
	private Integer campaignsent;
	private String campaignScheduleDate;
	private Date campaignScheduleDateInEdt;
	private String campaignEndDate;
	private Date campaignEndDateInEdt;
	private int campaignStatus;
	private String createdBy;
	private Date creationDate;
	private int eligiblecount;
	private Date modificationDate;
	private String modificedBy;
	private IopushTimeZone iopushTimeZone;
	private String title;
	private String description;
	private String forwardUrl;
	private String imagePath;
	private String campaign;
	private boolean segmented;
	private Set<IopushRules> iopushRules = new HashSet<IopushRules>(0);
	private boolean multiple_country = false;
	private int subCampaignsCount;
	private int live;
	boolean requireInteraction;
//  fields for Banner Image
	private boolean largeImage;
	private String bannerImage;


	private Set<IopushViewsClicks> iopushViewsClickses = new HashSet<IopushViewsClicks>(0);

	public IopushCampaign() {
	}


	public IopushCampaign(int campaignId,IopushProduct iopushProduct, int campaignStatus, int eligiblecount, Date modificationDate, IopushTimeZone fkTimezoneId) {
		this.campaignId = campaignId;
		this.iopushProduct=iopushProduct;
		this.campaignStatus = campaignStatus;
		this.eligiblecount = eligiblecount;
		this.modificationDate = modificationDate;
		this.iopushTimeZone = fkTimezoneId;
	}


	@Id 
	@SequenceGenerator(name="iopush_campaign_seq", sequenceName="iopush_campaign_seq",allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_campaign_seq")
	@Column(name = "campaign_id", unique = true, nullable = false,columnDefinition = "serial")
	public int getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(int campaignId) {
		this.campaignId = campaignId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="fk_product_id", nullable=false)
	public IopushProduct getIopushProduct() {
		return iopushProduct;
	}

	/**
	 * @param iopushProduct the iopushProduct to set
	 */
	public void setIopushProduct(IopushProduct iopushProduct) {
		this.iopushProduct = iopushProduct;
	}





	@Column(name="campaignclick", columnDefinition = "int default 0")
	public Integer getCampaignclick() {
		return this.campaignclick;
	}


	public void setCampaignclick(Integer campaignclick) {
		this.campaignclick = campaignclick;
	}



	@Column(name="reqiureInteraction")
	public boolean isRequireInteraction() {
		return requireInteraction;
	}
	public void setRequireInteraction(boolean requireInteraction) {
		this.requireInteraction = requireInteraction;
	}


	/**
	 * @return the multiple_cities
	 */

	@Column(name="is_multiple", nullable = false,columnDefinition="boolean default false")
	public boolean isMultiple_country() {
		return multiple_country;
	}


	/**
	 * @param multiple_cities the multiple_cities to set
	 */
	public void setMultiple_country(boolean multiple_cities) {
		this.multiple_country = multiple_cities;
	}


	@Column(name="campaignclose", columnDefinition = "int default 0")
	public Integer getCampaignclose() {
		return this.campaignclose;
	}

	public void setCampaignclose(Integer campaignclose) {
		this.campaignclose = campaignclose;
	}


	@Column(name="campaign_current_date", length=29)
	public String getCampaignCurrentDate() {
		return this.campaignCurrentDate;
	}

	public void setCampaignCurrentDate(String campaignCurrentDate) {
		this.campaignCurrentDate = campaignCurrentDate;
	}




	@Column(name="campaign_name", length=60)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Column(name="source", length=60)
	public String getSource() {
		return source;
	}


	public void setSource(String source) {
		this.source = source;
	}

	@Column(name="generic", length=60)
	public String getGeneric() {
		return generic;
	}


	public void setGeneric(String generic) {
		this.generic = generic;
	}


	@Column(name="campaignopen", columnDefinition = "int default 0")
	public Integer getCampaignopen() {
		return this.campaignopen;
	}

	public void setCampaignopen(Integer campaignopen) {
		this.campaignopen = campaignopen;
	}


	@Column(name="campaignsent", columnDefinition = "int default 0")
	public Integer getCampaignsent() {
		return this.campaignsent;
	}

	public void setCampaignsent(Integer campaignsent) {
		this.campaignsent = campaignsent;
	}


	@Column(name="campaign_schedule_date", length=29)
	public String getCampaignScheduleDate() {
		return this.campaignScheduleDate;
	}

	public void setCampaignScheduleDate(String campaignScheduleDate) {
		this.campaignScheduleDate = campaignScheduleDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="campaign_schedule_date_in_edt", length=29)
	public Date getCampaignScheduleDateInEdt() {
		return this.campaignScheduleDateInEdt;
	}

	public void setCampaignScheduleDateInEdt(Date campaignScheduleDateInEdt) {
		this.campaignScheduleDateInEdt = campaignScheduleDateInEdt;
	}

	@Column(name="campaign_end_date", length=29)
	public String getCampaignEndDate() {
		return campaignEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="campaign_end_date_in_edt", length=29)
	public Date getCampaignEndDateInEdt() {
		return campaignEndDateInEdt;
	}


	public void setCampaignEndDate(String campaignEndDate) {
		this.campaignEndDate = campaignEndDate;
	}


	public void setCampaignEndDateInEdt(Date campaignEndDateInEdt) {
		this.campaignEndDateInEdt = campaignEndDateInEdt;
	}


	@Column(name="campaign_status", nullable=false)
	public int getCampaignStatus() {
		return this.campaignStatus;
	}

	public void setCampaignStatus(int campaignStatus) {
		this.campaignStatus = campaignStatus;
	}


	@Column(name="created_by", length=50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="creation_date", length=29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}


	@Column(name="eligiblecount", nullable=false)
	public int getEligiblecount() {
		return this.eligiblecount;
	}

	public void setEligiblecount(int eligiblecount) {
		this.eligiblecount = eligiblecount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="modification_date", nullable=false, length=29)
	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}


	@Column(name="modificed_by", length=50)
	public String getModificedBy() {
		return this.modificedBy;
	}

	public void setModificedBy(String modificedBy) {
		this.modificedBy = modificedBy;
	}


	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="fk_timezone_id", nullable=false)
	public IopushTimeZone getIopushTimeZone() {
		return this.iopushTimeZone;
	}

	public void setIopushTimeZone(IopushTimeZone fkTimezoneId) {
		this.iopushTimeZone = fkTimezoneId;
	}


	@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushCampaign")
	public Set<IopushRules> getIopushRules() {
		return this.iopushRules;
	}

	public void setIopushRules(Set<IopushRules> iopushRules) {
		this.iopushRules = iopushRules;
	}


	@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushCampaign")
	public Set<IopushViewsClicks> getIopushViewsClickses() {
		return this.iopushViewsClickses;
	}

	public void setIopushViewsClickses(Set<IopushViewsClicks> iopushViewsClickses) {
		this.iopushViewsClickses = iopushViewsClickses;
	}


	@Column(name="description", length=200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	@Column(name="forward_url", length=200)
	public String getForwardUrl() {
		return this.forwardUrl;
	}

	public void setForwardUrl(String forwardUrl) {
		this.forwardUrl = forwardUrl;
	}


	@Column(name="image_path", length=100)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name="title", length=100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name="campaign", length=60)
	public String getCampaign() {
		return campaign;
	}


	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}


	@Column(name="is_segmented")
	public boolean isSegmented() {
		return segmented;
	}


	public void setSegmented(boolean segmented) {
		this.segmented = segmented;
	}


	@Column(name="subcampaign_count", nullable=false)
	public int getSubCampaignsCount() {
		return subCampaignsCount;
	}


	public void setSubCampaignsCount(int subCampaignsCount) {
		this.subCampaignsCount = subCampaignsCount;
	}

	@Column(name="live_subcampaigns", nullable=false)
	public int getLive() {
		return live;
	}


	public void setLive(int live) {
		this.live = live;
	}
	/**
	 * @return the largeImage
	 */
	@Column(name="large_image" )
	public boolean isLargeImage() {
		return largeImage;
	}


	/**
	 * @param largeImage the largeImage to set
	 */
	public void setLargeImage(boolean largeImage) {
		this.largeImage = largeImage;
	}


	/**
	 * @return the bannerImage
	 */
	@Column(name="banner_image", length=120)
	public String getBannerImage() {
		return bannerImage;
	}


	/**
	 * @param bannerImage the bannerImage to set
	 */
	public void setBannerImage(String bannerImage) {
		this.bannerImage = bannerImage;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "IopushCampaign [campaignId=" + campaignId + ", iopushProduct=" + iopushProduct
				+ ", campaignCurrentDate=" + campaignCurrentDate + ", campaignName=" + campaignName + ", source="
				+ source + ", generic=" + generic + ", campaignScheduleDate=" + campaignScheduleDate
				+ ", campaignScheduleDateInEdt=" + campaignScheduleDateInEdt + ", campaignEndDate=" + campaignEndDate
				+ ", campaignEndDateInEdt=" + campaignEndDateInEdt + ", campaignStatus=" + campaignStatus
				+ ", createdBy=" + createdBy + ", eligiblecount=" + eligiblecount + ", modificationDate="
				+ modificationDate + ", modificedBy=" + modificedBy + ", iopushTimeZone=" + iopushTimeZone + ", title="
				+ title + ", description=" + description + ", forwardUrl=" + forwardUrl + ", campaign=" + campaign
				+ ", segmented=" + segmented + ", iopushRules=" + iopushRules + ", subCampaignsCount="
				+ subCampaignsCount + ", live=" + live + ", requireInteraction=" + requireInteraction + ", largeImage="
				+ largeImage + "]";
	}

}


