package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IopushAuthority generated by hbm2java
 */
@Entity
@Table(name="iopush_authority"
    ,schema="public"
)
public class IopushAuthority  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int authId;
     private String authName;
//     private Set iopushAuthorityGroupMappings = new HashSet(0);

    public IopushAuthority() {
    }

	
    public IopushAuthority(int authId, String authName) {
        this.authId = authId;
        this.authName = authName;
    }
/*    public IopushAuthority(int authId, String authName, Set iopushAuthorityGroupMappings) {
       this.authId = authId;
       this.authName = authName;
       this.iopushAuthorityGroupMappings = iopushAuthorityGroupMappings;
    }
*/   
    @Id   
    @SequenceGenerator(name="iopush_authority_seq", sequenceName="iopush_authority_seq",allocationSize=1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_authority_seq")
 @Column(name = "auth_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getAuthId() {
        return this.authId;
    }
    
    public void setAuthId(int authId) {
        this.authId = authId;
    }

    
    @Column(name="auth_name", nullable=false, length=30)
    public String getAuthName() {
        return this.authName;
    }
    
    public void setAuthName(String authName) {
        this.authName = authName;
    }

/*@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushAuthority")
    public Set getIopushAuthorityGroupMappings() {
        return this.iopushAuthorityGroupMappings;
    }
    
    public void setIopushAuthorityGroupMappings(Set iopushAuthorityGroupMappings) {
        this.iopushAuthorityGroupMappings = iopushAuthorityGroupMappings;
    }

*/


}


