package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushGeoDetails generated by hbm2java
 */
@Entity
@Table(name="iopush_geo_details"
    ,schema="public"
)
public class IopushGeoDetails  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int geoId;
     private String createdBy;
     private Date creationDate;
     private String geoCode;
     private Double geoLatitude;
     private Double geoLongititude;
     private String geoName;
     private Date modificationDate;
     private String modificedBy;
     private Set<IopushCityDetails> iopushCityDetails = new HashSet<IopushCityDetails>(0);
     private Set<IopushSubscribers> iopushSubscribers = new HashSet<IopushSubscribers>(0);

    public IopushGeoDetails() {
    }

	
    public IopushGeoDetails(int geoId, Date modificationDate) {
        this.geoId = geoId;
        this.modificationDate = modificationDate;
    }
    public IopushGeoDetails(int geoId, String createdBy, Date creationDate, String geoCode, Double geoLatitude, Double geoLongititude, String geoName, Date modificationDate, String modificedBy, Set<IopushCityDetails> iopushCityDetailses, Set<IopushSubscribers> iopushSubscriberses) {
       this.geoId = geoId;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.geoCode = geoCode;
       this.geoLatitude = geoLatitude;
       this.geoLongititude = geoLongititude;
       this.geoName = geoName;
       this.modificationDate = modificationDate;
       this.modificedBy = modificedBy;
       this.iopushCityDetails = iopushCityDetailses;
       this.iopushSubscribers = iopushSubscriberses;
    }
   
    @Id   
    @SequenceGenerator(name="iopush_geo_details_seq", sequenceName="iopush_geo_details_seq",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_geo_details_seq")
    @Column(name = "geo_id", unique = true, nullable = false,columnDefinition = "serial")
    public int getGeoId() {
        return this.geoId;
    }
    
    public void setGeoId(int geoId) {
        this.geoId = geoId;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="geo_code", length=10)
    public String getGeoCode() {
        return this.geoCode;
    }
    
    public void setGeoCode(String geoCode) {
        this.geoCode = geoCode;
    }

    
    @Column(name="geo_latitude", precision=17, scale=17)
    public Double getGeoLatitude() {
        return this.geoLatitude;
    }
    
    public void setGeoLatitude(Double geoLatitude) {
        this.geoLatitude = geoLatitude;
    }

    
    @Column(name="geo_longititude", precision=17, scale=17)
    public Double getGeoLongititude() {
        return this.geoLongititude;
    }
    
    public void setGeoLongititude(Double geoLongititude) {
        this.geoLongititude = geoLongititude;
    }

    
    @Column(name="geo_name", length=20)
    public String getGeoName() {
        return this.geoName;
    }
    
    public void setGeoName(String geoName) {
        this.geoName = geoName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modification_date", nullable=false, length=29)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="modificed_by", length=50)
    public String getModificedBy() {
        return this.modificedBy;
    }
    
    public void setModificedBy(String modificedBy) {
        this.modificedBy = modificedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushGeoDetails")
    public Set<IopushCityDetails> getIopushCityDetails() {
        return this.iopushCityDetails;
    }
    
    public void setIopushCityDetails(Set<IopushCityDetails> iopushCityDetails) {
        this.iopushCityDetails = iopushCityDetails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iopushGeoDetails")
    public Set<IopushSubscribers> getIopushSubscribers() {
        return this.iopushSubscribers;
    }
    
    public void setIopushSubscribers(Set<IopushSubscribers> iopushSubscribers) {
        this.iopushSubscribers = iopushSubscribers;
    }




}


