package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IopushActivesubscribers generated by hbm2java
 */
@Entity
@Table(name="iopush_activesubscribers"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"iopush_token", "fk_campaign_id"}) 
)
public class IopushActivesubscribers  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
     private Integer campaignclick;
     private Integer campaignclose;
     private Integer campaignopen;
     private Integer campaignsent;
     private String fcmToken;
     private int fkCityid;
     private int fkGeoid;
     private int fkPlatformid;
     private int status;
     
     private String iopushToken;
     private int fkCampaignId;
    private int fk_segmentId;
    
    public IopushActivesubscribers() {
    }

	
    public IopushActivesubscribers(int id, int fkCityid, int fkGeoid, int fkPlatformid, int status, int fkCampaignId) {
        this.id = id;
        this.fkCityid = fkCityid;
        this.fkGeoid = fkGeoid;
        this.fkPlatformid = fkPlatformid;
        this.status = status;
        this.fkCampaignId = fkCampaignId;
    }
    public IopushActivesubscribers(int id, Integer campaignclick, Integer campaignclose, Integer campaignopen, Integer campaignsent, int fkCityid, int fkGeoid, int fkPlatformid, int status, String iopushToken, int fkCampaignId) {
       this.id = id;
       this.campaignclick = campaignclick;
       this.campaignclose = campaignclose;
       this.campaignopen = campaignopen;
       this.campaignsent = campaignsent;
       this.fkCityid = fkCityid;
       this.fkGeoid = fkGeoid;
       this.fkPlatformid = fkPlatformid;
       this.status = status;
       this.iopushToken = iopushToken;
       this.fkCampaignId = fkCampaignId;
    }
   
    @Id   
    @SequenceGenerator(name="iopush_activesubscribers_seq", sequenceName="iopush_activesubscribers_seq",allocationSize=1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_activesubscribers_seq")
 @Column(name = "id", unique = true, nullable = false,columnDefinition = "serial")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="campaignclick")
    public Integer getCampaignclick() {
        return this.campaignclick;
    }
    
    public void setCampaignclick(Integer campaignclick) {
        this.campaignclick = campaignclick;
    }

    
    @Column(name="campaignclose")
    public Integer getCampaignclose() {
        return this.campaignclose;
    }
    
    public void setCampaignclose(Integer campaignclose) {
        this.campaignclose = campaignclose;
    }

    
    @Column(name="campaignopen")
    public Integer getCampaignopen() {
        return this.campaignopen;
    }
    
    public void setCampaignopen(Integer campaignopen) {
        this.campaignopen = campaignopen;
    }

    
    @Column(name="campaignsent")
    public Integer getCampaignsent() {
        return this.campaignsent;
    }
    
    public void setCampaignsent(Integer campaignsent) {
        this.campaignsent = campaignsent;
    }

    
    @Column(name="fk_cityid", nullable=false)
    public int getFkCityid() {
        return this.fkCityid;
    }
    
    public void setFkCityid(int fkCityid) {
        this.fkCityid = fkCityid;
    }

    
    @Column(name="fk_geoid", nullable=false)
    public int getFkGeoid() {
        return this.fkGeoid;
    }
    

    @Column(name="fk_segmentid", nullable=false)
	public int getFk_segmentId() {
		return fk_segmentId;
	}


	/**
	 * @param fk_segmentId the fk_segmentId to set
	 */
	public void setFk_segmentId(int fk_segmentId) {
		this.fk_segmentId = fk_segmentId;
	}


	public void setFkGeoid(int fkGeoid) {
        this.fkGeoid = fkGeoid;
    }

    
    @Column(name="fk_platformid", nullable=false)
    public int getFkPlatformid() {
        return this.fkPlatformid;
    }
    
    public void setFkPlatformid(int fkPlatformid) {
        this.fkPlatformid = fkPlatformid;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="iopush_token")
    public String getIopushToken() {
        return this.iopushToken;
    }
    
    public void setIopushToken(String iopushToken) {
        this.iopushToken = iopushToken;
    }

    
    @Column(name="fk_campaign_id", nullable=false)
    public int getFkCampaignId() {
        return this.fkCampaignId;
    }
    
    public void setFkCampaignId(int fkCampaignId) {
        this.fkCampaignId = fkCampaignId;
    }

    @Column(name="fcm_token", nullable=false)
    public String getFcmToken() {
        return this.fcmToken;
    }
    
    public void setFcmToken(String fcmToken) {
        this.fcmToken = fcmToken;
    }


}


