package com.saphire.iopush.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IopushPayPalPayment generated by hbm2java
 */
@Entity
@Table(name="iopush_user_plan_selected"
    ,schema="public")
public class IopushPayPalPlanSelected {

 
//private IopushUserplan iopushUserplan;
private IopushProduct iopushProduct;
private IopushPayPalPayment iopushPayPalPayment;
private int subscriberLimit;
private double planCost;
private int id;




@Id 
@SequenceGenerator(name="iopush_plan_selected", sequenceName="iopush_plan_selected",allocationSize=1)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_plan_selected")
@Column(name = "id", unique = true, nullable = false,columnDefinition = "serial")
public int getId() {
	return id;
}
public void setId(int id) {
	this.id = id;
}
/*@OneToOne(fetch=FetchType.LAZY)
@JoinColumn(name="fk_plan_id", nullable=false)
public IopushUserplan getIopushUserplan() {
	return iopushUserplan;
}
public void setIopushUserplan(IopushUserplan iopushUserplan) {
	this.iopushUserplan = iopushUserplan;
}*/

@OneToOne(fetch=FetchType.LAZY)
@JoinColumn(name="fk_product_id", nullable=false)
public IopushProduct getIopushProduct() {
	return iopushProduct;
}
public void setIopushProduct(IopushProduct iopushProduct) {
	this.iopushProduct = iopushProduct;
}

@OneToOne(fetch=FetchType.LAZY)
@JoinColumn(name="fk_payment_id", nullable=false)
public IopushPayPalPayment getIopushPayPalPayment() {
	return iopushPayPalPayment;
}
public void setIopushPayPalPayment(IopushPayPalPayment iopushPayPalPayment) {
	this.iopushPayPalPayment = iopushPayPalPayment;
}

@Column(name="subscribers_limit")
public int getSubscriberLimit() {
	return subscriberLimit;
}
public void setSubscriberLimit(int subscriberLimit) {
	this.subscriberLimit = subscriberLimit;
}

@Column(name="plan_cost")
public double getPlanCost() {
	return planCost;
}
public void setPlanCost(double pricing) {
	this.planCost= pricing;
}
@Override
public String toString() {
	return "IopushPayPalPlanSelectedTable [ iopushProduct=" + iopushProduct
			+ ", iopushPayPalPayment=" + iopushPayPalPayment + ", subscriberLimit=" + subscriberLimit + ", planCost="
			+ planCost + "]";
}


 
}
