package com.saphire.iopush.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IopushPayPalPayment generated by hbm2java
 */
@Entity
@Table(name="iopush_paypal_payment"
    ,schema="public"
)
public class IopushPayPalPayment {

 
 
 @Override
	public String toString() {
		return "IopushPayPalPayment [invoice_no=" + invoice_no + ", payment_method=" + payment_method + ", total_amt="
				+ total_amt + ", currency=" + currency + ", create_date=" + create_date + ", createBy=" + createBy
				+ ", iopushUserplan=" + iopushUserplan + ", iopushProduct=" + iopushProduct + ", status=" + status
				+ ", reason=" + reason + ", paypal_ack=" + paypal_ack + ", payment_url=" + payment_url + ", payment_id="
				+ payment_id + ", paypal_payment_id=" + paypal_payment_id + ", accessToken=" + accessToken + "]";
	}
 private String invoice_no;
 private String payment_method;
 private double total_amt;
 private String currency;
 private Date create_date;
 private String createBy;
 private IopushUserplan iopushUserplan;
 private IopushProduct iopushProduct;
 private int status;
 private String reason;
 private int paypal_ack;
 private String payment_url;
 private int payment_id;
 private String paypal_payment_id;
 private String accessToken;
 
 
 
 @Column(name="access_token",length=200)
 public String getAccessToken() {

return accessToken;
 }
 
 public void setAccessToken(String accessToken) {
  this.accessToken = accessToken;
 }
 
 @OneToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="fk_product_id", nullable=false)
 public IopushProduct getIopushProduct() {
	return iopushProduct;
}
public void setIopushProduct(IopushProduct iopushProduct) {
	this.iopushProduct = iopushProduct;
}

@Column(name="paypal_payment_id", length=100)
public String getPaypal_payment_id() {
	return paypal_payment_id;
}
public void setPaypal_payment_id(String paypal_payment_id) {
	this.paypal_payment_id = paypal_payment_id;
}
@Column(name="invoiceNumber", length=100)
public String getInvoice_no() {
	return invoice_no;
}
public void setInvoice_no(String invoice_no) {
	this.invoice_no = invoice_no;
}

@Column(name="payment_method", length=100)
public String getPayment_method() {
	return payment_method;
}
public void setPayment_method(String payment_method) {
	this.payment_method = payment_method;
}

@Column(name="payment_amount")
public double getTotal_amt() {
	return total_amt;
}
public void setTotal_amt(double total_amt) {
	this.total_amt = total_amt;
}

@Column(name="currency")
public String getCurrency() {
	return currency;
}
public void setCurrency(String currency) {
	this.currency = currency;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name="creation_date", length=29)
public Date getCreate_date() {
	return create_date;
}
public void setCreate_date(Date create_date) {
	this.create_date = create_date;
}


@Column(name="created_by", length=50)
public String getCreateBy() {
	return createBy;
}
public void setCreateBy(String createBy) {
	this.createBy = createBy;
}


@OneToOne(fetch=FetchType.LAZY)
@JoinColumn(name="fk_plan_id", nullable=false)
public IopushUserplan getIopushUserplan() {
	return iopushUserplan;
}
public void setIopushUserplan(IopushUserplan iopushUserplan) {
	this.iopushUserplan = iopushUserplan;
}



@Column(name="payment_status")
public int getStatus() {
	return status;
}
public void setStatus(int status) {
	this.status = status;
}

@Column(name="payment_reason")
public String getReason() {
	return reason;
}
public void setReason(String reason) {
	this.reason = reason;
}

@Column(name="payment_ack")
public int getPaypal_ack() {
	return paypal_ack;
}
public void setPaypal_ack(int paypal_ack) {
	this.paypal_ack = paypal_ack;
}

@Column(name="payment_url")
public String getPayment_url() {
	return payment_url;
}
public void setPayment_url(String payment_url) {
	this.payment_url = payment_url;
}

@Id 
@SequenceGenerator(name="iopush_paypalPayment_seq", sequenceName="iopush_paypalPayment_seq",allocationSize=1)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_paypalPayment_seq")
@Column(name = "payment_id", unique = true, nullable = false,columnDefinition = "serial")
public int getPayment_id() {
	return payment_id;
}
public void setPayment_id(int payment_id) {
	this.payment_id = payment_id;
}
 
 
 
}
