package com.saphire.iopush.model;
// Generated 24 Jan, 2017 10:27:42 PM by Hibernate Tools 3.4.0.CR1



import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

import javax.persistence.TemporalType;



/**
 * IopushActivesubscribers generated by hbm2java
 */
@Entity
@Table(name="iopush_rssfeed_config",schema="public")
public class IopushRssFeedConfig  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	String name;
    String url;
    String campaign;
	String source;
	String generic;
	private String countries;
	private String cities;
	private String products;
	private String isps;
	private String platform;
	private int notification;
	private String createdBy;
    private Date creationDate;
    private Date modificationDate;
    private String modificedBy;
    private int automatedImage;
    private String logo_path; 
    private String segments;
    private String segmentTypes;
    private String subscribedFrom;
    
    @Column(name="automatedImage")
    public int getAutomatedImage() {
		return automatedImage;
	}




	public void setAutomatedImage(int automatedImage) {
		this.automatedImage = automatedImage;
	}




	public IopushRssFeedConfig() {
    }

	
   
   
    @Id   
    @SequenceGenerator(name="iopush_rssfeed_config_seq", sequenceName="iopush_rssfeed_config_seq",allocationSize=1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="iopush_rssfeed_config_seq")
 @Column(name = "id", unique = true, nullable = false,columnDefinition = "serial")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }




	
    @Column(name="segments_id",length=500)
    public String getSegments() {
		return segments;
	}




	/**
	 * @param segments the segments to set
	 */
	public void setSegments(String segments) {
		this.segments = segments;
	}




	/**
	 * @return the segmentTypes
	 */
    @Column(name="segmentTypes_id",length=500)
	public String getSegmentTypes() {
		return segmentTypes;
	}




	/**
	 * @param segmentTypes the segmentTypes to set
	 */
	public void setSegmentTypes(String segmentTypes) {
		this.segmentTypes = segmentTypes;
	}


	/**
	 * @return the countries
	 */
    @Column(name="country",length=150)
	public String getCountries() {
		return countries;
	}




	/**
	 * @return the cities
	 */
    @Column(name="city",length=150)
	public String getCities() {
		return cities;
	}




	/**
	 * @return the isps
	 */
    @Column(name="isp",length=150)
	public String getIsps() {
		return isps;
	}




	/**
	 * @return the platform
	 */
    @Column(name="platform",length=150)
	public String getPlatform() {
		return platform;
	}




	


	/**
	 * @return the notification
	 */
    @Column(name="notification")
	public int getNotification() {
		return notification;
	}




	/**
	 * @return the name
	 */
    @Column(name="name",length=150)
	public String getName() {
		return name;
	}




	/**
	 * @return the url
	 */
    @Column(name="url",length=400)
	public String getUrl() {
		return url;
	}




	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}




	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}




	/**
	 * @return the products
	 */
    @Column(name="products",length=150)
	public String getProducts() {
		return products;
	}




	/**
	 * @return the campaign
	 */
    @Column(name="campaign",length=150)
	public String getCampaign() {
		return campaign;
	}




	/**
	 * @return the source
	 */
    @Column(name="source",length=150)
	public String getSource() {
		return source;
	}




	/**
	 * @return the generic
	 */
    @Column(name="generic",length=150)
	public String getGeneric() {
		return generic;
	}




	/**
	 * @param campaign the campaign to set
	 */
	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}




	/**
	 * @param source the source to set
	 */
	public void setSource(String source) {
		this.source = source;
	}




	/**
	 * @param generic the generic to set
	 */
	public void setGeneric(String generic) {
		this.generic = generic;
	}




	/**
	 * @param products the products to set
	 */
	public void setProducts(String products) {
		this.products = products;
	}




	/**
	 * @param notification the notification to set
	 */
	public void setNotification(int notification) {
		this.notification = notification;
	}




	

	/**
	 * @param countries the countries to set
	 */
	public void setCountries(String countries) {
		this.countries = countries;
	}




	/**
	 * @param cities the cities to set
	 */
	public void setCities(String cities) {
		this.cities = cities;
	}




	/**
	 * @param isps the isps to set
	 */
	public void setIsps(String isps) {
		this.isps = isps;
	}




	/**
	 * @param platform the platform to set
	 */
	public void setPlatform(String platform) {
		this.platform = platform;
	}




	

	 @Temporal(TemporalType.TIMESTAMP)
	    @Column(name="modification_date", nullable=false, length=29)
	    public Date getModificationDate() {
	        return this.modificationDate;
	    }
	    
	    public void setModificationDate(Date modificationDate) {
	        this.modificationDate = modificationDate;
	    }

	    
	    @Column(name="modificed_by", length=50)
	    public String getModificedBy() {
	        return this.modificedBy;
	    }
	    
	    public void setModificedBy(String modificedBy) {
	        this.modificedBy = modificedBy;
	    }
	    
	    @Column(name="created_by", length=50)
	    public String getCreatedBy() {
	        return this.createdBy;
	    }
	    
	    public void setCreatedBy(String createdBy) {
	        this.createdBy = createdBy;
	    }

	    @Temporal(TemporalType.TIMESTAMP)
	    @Column(name="creation_date", length=29)
	    public Date getCreationDate() {
	        return this.creationDate;
	    }
	    
	    public void setCreationDate(Date creationDate) {
	        this.creationDate = creationDate;
	    }



	    @Column(name="logo_path",length=170)
		public String getLogo_path() {
			return logo_path;
		}




		public void setLogo_path(String logo_path) {
			this.logo_path = logo_path;
		}



		@Column(name="subscribed_from",length=30)
		public String getSubscribedFrom() {
			return subscribedFrom;
		}




		public void setSubscribedFrom(String subscribedFrom) {
			this.subscribedFrom = subscribedFrom;
		}
		
		
		

}

